apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.app_name }}
  description: A python hello world application named ${{ values.app_name }} running in ${{ values.app_env }} environment
  # Example for optional annotations
  annotations:
    github.com/project-slug: learners-codetree/${{ values.app_name }}
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: development
  lifecycle: experimental